name = input("please enter your name: ")
print("Your name is", name)
age = int(input("please enter your age: "))
print("You are", age)
print("in 5 years you will be", age + 5)
print("----------------------------------")
print(name, "is ", age, "year's old")
